
import keyMirror from '../../utils/key-mirror';

export default keyMirror('TEMPLATES_GENERATOR', [
    'USER_LOADING_REQUEST',
    'USER_LOADING_SUCCESS',
    'USER_LOADING_FAILURE',
    'GENRES_LOADING_REQUEST',
    'GENRES_LOADING_SUCCESS',
    'GENRES_LOADING_FAILURE',
    'PREVIEW_REQUEST',
    'PREVIEW_SUCCESS',
    'PREVIEW_FAILURE',
    'PREVIEW_CLEAR_RESULT',
    'SAVE_REQUEST',
    'SAVE_SUCCESS',
    'SAVE_FAILURE',
    'SAVE_CLEAR_RESULT',
    'UPDATE_REQUEST',
    'UPDATE_SUCCESS',
    'UPDATE_FAILURE',
    'TEMPLATES_REQUEST',
    'TEMPLATES_SUCCESS',
    'TEMPLATES_FAILURE',
    'TEMPLATES_REMOVE_REQUEST',
    'TEMPLATES_REMOVE_SUCCESS',
    'TEMPLATES_REMOVE_FAILURE',
    'CLEAR_STORE',
]);
