
import keyMirror from '../../utils/key-mirror';

export default keyMirror('TEMPLATES_GENERATOR', [
    'USER_LOADING_REQUEST',
    'USER_LOADING_SUCCESS',
    'USER_LOADING_ERROR',
    'GENRES_LOADING_REQUEST',
    'GENRES_LOADING_SUCCESS',
    'GENRES_LOADING_ERROR',
    'UPLOAD_REQUEST',
    'UPLOAD_SUCCESS',
    'UPLOAD_ERROR',
    'UPLOAD_CLEAR_RESULT',
    'SAVE_REQUEST',
    'SAVE_SUCCESS',
    'SAVE_ERROR',
    'SAVE_CLEAR_RESULT',
    'TEMPLATES_REQUEST',
    'TEMPLATES_SUCCESS',
    'TEMPLATES_ERROR',
    'TEMPLATES_REMOVE_REQUEST',
    'TEMPLATES_REMOVE_SUCCESS',
    'TEMPLATES_REMOVE_ERROR',
    'CLEAR_STORE',
]);
