
import keyMirror from '../../utils/key-mirror';

export default keyMirror('QUOTES_LOADER', [
    'QUOTES_LOADING_REQUEST',
    'QUOTES_LOADING_SUCCESS',
    'QUOTES_LOADING_ERROR',
    'USER_LOADING_REQUEST',
    'USER_LOADING_SUCCESS',
    'USER_LOADING_ERROR',
    'GENRES_LOADING_REQUEST',
    'GENRES_LOADING_SUCCESS',
    'GENRES_LOADING_ERROR',
    'QUOTES_SET',
    'QUOTE_REMOVE',
    'QUOTES_START_UPLOAD',
    'QUOTE_UPLOADING_REQUEST',
    'QUOTE_UPLOADING_SUCCESS',
    'QUOTE_UPLOADING_ERROR',
    'QUOTES_UPLOADING_DONE',
    'QUOTES_UPLOADING_CLEAR_STATE',
    'CLEAR_STORE',
]);
